layout splits
launch --var window=first --cwd="~/code/yaarz/front" yarn dev
launch --location=vsplit --cwd="~/code/yaarz/front" yarn storybook
launch --location=hsplit --cwd="~/code/yaarz/front" npx tsc --watch --noEmit
focus_matching_window var:window=first
launch --title "app" --location=hsplit --cwd="~/code/yaarz/server" make livereload
focus

new_tab v:front
cd ~/code/yaarz/front
launch nvim

new_tab git
cd ~/code/yaarz
launch lazygit

new_tab zsh
cd ~/code/yaarz
launch zsh

new_tab v:server
cd ~/code/yaarz/server
launch nvim

new_tab v:db
cd ~/code/yaarz/server
launch nvim +DBUI
